Modify condition to check output format
fosslight/fosslight_util pull request #116
Opened 2023-05-16 23:34 UTC by bjk7119

## Description

- Modify condition to check output format

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Documentation update
- [ ] Refactoring, Maintenance
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

2023-05-16 23:52 UTC, soimkim commented
@bjk7119 님이 다시 수정 중~

2023-05-17 05:21 UTC, dd-jy approved these changes

2023-05-17 05:38 UTC, soimkim requested changes

2023-05-17 05:38 UTC, soimkim commented on src/fosslight_util/output_format.py
> +                    _ext = support_format.get(f'{format}', 'None')
SUPPORT_FORMAT 은 모두 소문자로 표기합니다. 통일성을 위해 none으로 표기할 것을 제안드립니다.

2023-05-17 05:38 UTC, soimkim commented on src/fosslight_util/output_format.py
> +                        msg = f"Enter the same extension of output file(-o:'{output}') with format(-f:'{format}')."
이 case는 -f 와 -o이 다른 case가 아니고
-f 로 입력 받은 포맷이 SUPPORT_FORMAT 에 없는 경우로 보입니다.
이에 msg가 하기 사항과 같아야하는 것이 아닌지 문의드립니다. 
 msg = 'Enter the supported format with -f option: ' + ', '.join(list(support_format.keys()))

2023-05-17 05:38 UTC, soimkim commented on src/fosslight_util/output_format.py
> +                    _ext = support_format.get(f'{format}', 'None')
none 대신 None으로 하여
 elif _ext == 'None': 를  elif not _ext: 로 표기해도 좋을듯합니다.

2023-05-17 05:38 UTC, soimkim commented on src/fosslight_util/output_format.py
> +                    _ext = support_format.get(f'{format}', 'None')
추가로 이미 output_extension 에 값을 가져온 사항인데, _ext로 다시 가져올 필요가 있나? 싶습니다.

2023-05-17 05:38 UTC, soimkim commented on src/fosslight_util/output_format.py
> +                        msg = f"Enter the same extension of output file(-o:'{output}') with format(-f:'{format}')."
이미 29 line에서 체크한 사항이라 이 elif에 들어올 case는 없을 것 같습니다.

2023-05-17 05:48 UTC, soimkim commented
Test cases 하기 사항 테스트 후 리뷰 요청 부탁드려요~
1. -f excel -o test.csv
    Enter the same extension of output file(-o:'{output}') with format(-f:'{format}')
2. -f none-format
    Enter the supported format with -f option:... 
3. -o none.png
     Enter the supported file extension:
4. -f opossum -o success.json : 성공
6. -f spdx-json -o success.json : 성공

2023-05-17 06:05 UTC, bjk7119 commented
![image](https://github.com/fosslight/fosslight_util/assets/81218204/d94d1637-1222-410d-831f-8f4bde708c15)
![image](https://github.com/fosslight/fosslight_util/assets/81218204/75cac675-b59c-4a26-a997-3ab48d113cad)

2023-05-17 06:16 UTC, soimkim commented on src/fosslight_util/output_format.py
> +                    if not find_ext:
find_ext 를 아예 지우고,
if not find_ext:를 if basename_extension not in support_format.values(): 으로 쓰는 것은 어떤지요?

2023-05-17 06:21 UTC, soimkim approved these changes

2023-05-17 06:23 UTC, merged