Add github token authentication
fosslight/fosslight_util pull request #157
Opened 2024-04-21 11:54 UTC by SeongjunJo

## Description
* Add github token argument
* Add pygit2 github authentication

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Documentation update
- [ ] Refactoring, Maintenance
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

2024-04-22 00:48 UTC, soimkim requested changes

2024-04-22 00:48 UTC, soimkim commented on src/fosslight_util/download.py
> +def cli_download_and_extract(link: str, target_dir: str, log_dir: str, git_token: str = "", checkout_to: str = "",
@SeongjunJo , 추가된 parameter는 맨 마지막으로 이동해야 합니다.
다른 Scanner에서 4번째 parameter로 checkout_to를 입력하여 사용할 수 있ㅅ브니다.

2024-04-22 00:48 UTC, soimkim commented on src/fosslight_util/download.py
> +def download_git_clone(git_url, target_dir, git_token="", checkout_to="", tag="", branch=""):
@SeongjunJo , 추가된 parameter를 맨 마지막으로 이동하여주십시오.

2024-04-22 00:51 UTC, soimkim commented on src/fosslight_util/download.py
> +    user_name = oss_name.split('-')[0]
@SeongjunJo , git_url에 사용자의 user_name이 포함되지 않을 수 있습니다. 
예를 들어 git@github.com:LGE-OSS/risk_prevention.git 는 private git 이지만 ssh url에 user_name이 포함되지 않습니다.

별도로 입력 받아야하는 것이 아닌지 검토해주십시오.

2024-04-22 01:00 UTC, soimkim commented
@SeongjunJo , https://kettan007.medium.com/how-to-clone-a-git-repository-using-personal-access-token-a-step-by-step-guide-ab7b54d4ef83를 보니 user name, token을 별도로 입력 받는 대신 token을 url로 입력하는 방법도 있습니다. 

`git clone https://<TOKEN>@github.com/username/repo.git`

위 방식으로 private git을 다운로드 가능하다면, private git 다운로드 실패시 안내 문구로 사용자에게 url에 token을 입력하도록 안내하는 방법도 있습니다.

2024-04-22 01:01 UTC, soimkim commented
추가로 tox -e release시, 에러가 없도록 해주십시오. 
![image](https://github.com/fosslight/fosslight_util/assets/4284712/5685fbb4-b377-44fd-b121-1a6ee41e3444)

2024-04-26 03:36 UTC, soimkim commented
@SeongjunJo 님, url에서 username을 추출하고 있는 것으로보입니다. 기존 커맨트로 리뷰 드린 사항에 답변 부탁드립니다.

2024-04-26 07:14 UTC, soimkim commented
@SeongjunJo , 리포트해주신 ssh 링크에 대해 다운로드 시도 안 하는 버그 fix해두었습니다. : https://github.com/fosslight/fosslight_util/pull/158

위 수정이 반영되어도 ssh 링크는 다운로드 안 되는 상태입니다.
성준님 수정으로 token 이용한 ssh 다운로드가 반영되면 다운로드 될 것으로 보입니다. 

참고하여주십시오.

2024-04-30 17:20 UTC, SeongjunJo commented
@soimkim 수정하였습니다. 확인 부탁드립니다.

2024-04-30 17:34 UTC, closed without merging