Add the function to compare yaml
fosslight/fosslight_util pull request #74
Opened 2022-06-14 14:41 UTC by dd-jy

## Description

### Add the function to compare yaml.

Result of  tests/test_compare_yaml.py : 
```
{'add': [['new-test-oss', [['1.0.1', 'Apache-2.0,MIT']]]], 'delete': [['del-test-oss', [['1.0.1', 'Apache-2.0,MIT']]]], 'update': [['add-license-oss', [['0.5.6', 'Apache-2.0,MPL-2.0']], [['0.5.3', 'Apache-2.0'], ['0.5.3', 'MPL-2.0']]], ['go:github.com/konsorten/go-windows-terminal-sequences', [['1.0.1', 'MIT']], [['1.0.1', 'Apache-2.0,MIT']]]]}
```

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Documentation update
- [ ] Refactoring, Maintenance
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

2022-06-29 00:00 UTC, soimkim requested changes

2022-06-29 00:00 UTC, soimkim commented on src/fosslight_util/compare_yaml.py
> +_version = 'version'
(Minor) It is recommended to use capital letters when declaring constants.
`_version` -> `VERSION`
- Ref. https://pep8.org/#constants

2022-06-29 00:00 UTC, soimkim commented on src/fosslight_util/compare_yaml.py
> +        item_info = {_name: oi.name, _version: oi.version, _license: oi.license}
(Minor) I recommend the followings:
_name ->name, _version -> version, _license -> license
> _single_leading_underscore: weak “internal use” indicator. E.g. from M import * does not import objects whose name starts with an underscore.

- Ref. https://pep8.org/#descriptive-naming-styles

2022-06-29 00:00 UTC, soimkim commented on src/fosslight_util/compare_yaml.py
> +    _add = "add"
(Minor) It is recommended to use capital letters when declaring constants.
_add -> ADD

Ref. https://pep8.org/#constants

2022-06-29 00:00 UTC, soimkim commented on src/fosslight_util/compare_yaml.py
> +    before_oss_items, _ = parsing_yml(os.path.basename(before_file), os.path.dirname(before_file))
parsing_yml(os.path.basename(before_file), os.path.dirname(before_file))
-> parsing_yml(before_file, os.path.dirname(before_file))

2022-06-29 00:08 UTC, soimkim commented on tests/test_compare_yaml.py
> +    print(compare_yaml(os.path.join(cur, 'before.yaml'), os.path.join(cur, 'after.yaml')))
(Minor) This is better for analyzing the results.
``` 
import json
result = compare_yaml(os.path.join(cur, 'before.yaml'), os.path.join(cur, 'after.yaml'))
print(json.dumps(result, indent=4, sort_keys=True))
```

2022-06-30 01:01 UTC, dd-jy commented
@soimkim 
Thanks for reveiwing! I changed everything.

2022-07-01 07:36 UTC, soimkim commented on src/fosslight_util/compare_yaml.py
> +    removed_name = [bn for bn in b_name if bn not in a_name]
[Minor] There seems to be no need to convert it to a list.
ex.
```
    b_name = set([bi[NAME] for bi in new_before])
    a_name = set([ai[NAME] for ai in after_items])
    removed_name = b_name - a_name
    changed_name = b_name ^ removed_name
    added_name = a_name ^ changed_name
```

2022-07-01 07:45 UTC, soimkim commented on src/fosslight_util/compare_yaml.py
> +    removed_name = [bn for bn in b_name if bn not in a_name]
1 more opinion.
Can't the following be changed to the difference set?
NOW: 
```    
changed_name = b_name ^ removed_name
added_name = a_name ^ changed_name
```
TO-BE:
```    
changed_name = b_name - removed_name
added_name = a_name - changed_name
```

2022-07-01 08:00 UTC, soimkim commented on src/fosslight_util/compare_yaml.py
> +            for ci in comp_out[CHANGE]:
How about changing the inside of `elif bi[NAME] in changed_name` like this?
```
            name_find = False
            for ci in comp_out[CHANGE]:
                if ci[NAME] == bi[NAME]:
                    bi.pop(NAME)
                    ci[PREV].append(bi)
                    name_find = True
                    break

            if not name_find:
                item_info = {NAME: bi[NAME], PREV: [], NOW: []}
                bi.pop(NAME)
                item_info[PREV].append(bi)
                comp_out[CHANGE].append(item_info)
```
TO-BE:
```
            filtered = next(filter(lambda oss_dict: oss_dict['name'] == bi[NAME], comp_out[CHANGE]), None)
            if filtered:
                bi.pop(NAME)
                filtered[PREV].append(bi)
                name_find = True
            else:
                item_info = {NAME: bi[NAME], PREV: [], NOW: []}
                bi.pop(NAME)
                item_info[PREV].append(bi)
                comp_out[CHANGE].append(item_info)
```

2022-07-01 08:09 UTC, soimkim commented on src/fosslight_util/compare_yaml.py
> +        elif ai[NAME] in changed_name:
How about changing the inside of `elif ai[NAME] in changed_name `like this?
AS-IS:
```
 for ci in comp_out[CHANGE]:
                if ci[NAME] == ai[NAME]:
                    ai.pop(NAME)
                    ci[NOW].append(ai)
                    break
```
TO-BE:
```
            filtered = next(filter(lambda oss_dict: oss_dict[NAME] == ai[NAME], comp_out[CHANGE]), None)
            if filtered:
                ai.pop(NAME)
                filtered[NOW].append(ai)
```

2022-07-01 08:14 UTC, soimkim commented on src/fosslight_util/compare_yaml.py
> +                    bi.pop(NAME)
[Question] Why is `bi.pop(NAME)` called?

2022-07-01 08:30 UTC, soimkim commented on src/fosslight_util/compare_yaml.py
> +                    bi.pop(NAME)
For printing!! 👍

2022-07-06 02:57 UTC, merged